### ISSUE TITLE
 注册sesison事件后 select不触发导致文件不会发送

### ISSUE THREAD

**Issue by sheepsleep** [RT-Thread-packages/webnet#26]
https://github.com/RT-Thread-packages/webnet/blob/5491546f9f859042fd91c8adf3911a32feb23e9e/src/wn_module.c#L407

  /*
     * set session write context
     */
    if (request->method != WEBNET_HEADER)
    {
        /* set dofile session ops */
        session->session_event_mask = WEBNET_EVENT_WRITE;
        session->user_data = (rt_uint32_t)fd;
        session->session_ops = &_dofile_ops;
    }
这里注册了发送文件的事件   等到下一次select后才会执行，没有新的select事件_dofile_ops则不会被调用
现象是浏览器请求html文件后，webnet会应答头部数据 此时浏览器等待文件内容  而webnet在等待下一次select触发，浏览器一直等待。  新建浏览器窗口请求webnet后 webnet会立即响应上次的sesseion没发出去的数据浏览器正确收到数据。  
我在注册这个ops后立即调用_dofile_ops 可以解决这个问题 但是是阻塞的影响响应速度  应该有更好的办法

**Comment by sheepsleep** [comment]
可能是W5500 api对select支持不好导致的

**Comment by aozima** [comment]
@sheepsleep 你用非W5500的测试下，如lwip的。

**Comment by sheepsleep** [comment]
> @sheepsleep 你用非W5500的测试下，如lwip的。

现在我这样改了下 能用了  不等下一次select触发 直接发index.html文件  收到浏览器请求后发送header 并立即发文件内容
`    if (request->method != WEBNET_HEADER)
    {
        //LOG_D("****webnet_module_system_dofile request->method != WEBNET_HEADER register write event" );
        /* set dofile session ops */
        session->session_event_mask = WEBNET_EVENT_WRITE;
        session->user_data = (rt_uint32_t)fd;
        session->session_ops = &_dofile_ops;
        //*** leon zhang added
        session->session_ops->session_handle(session, WEBNET_EVENT_WRITE);
        //LOG_D("****webnet_module_system_dofile handled session->phase=%d",session->session_phase);`

**Comment by sheepsleep** [comment]
现在我这样改了下 能用了 不等下一次select触发 直接发index.html文件 收到浏览器请求后发送header 并立即发文件内容
    if (request->method != WEBNET_HEADER)
    {
        //LOG_D("****webnet_module_system_dofile request->method != WEBNET_HEADER register write event" );
        /* set dofile session ops */
        session->session_event_mask = WEBNET_EVENT_WRITE;
        session->user_data = (rt_uint32_t)fd;
        session->session_ops = &_dofile_ops;
        //***  added by me
        session->session_ops->session_handle(session, WEBNET_EVENT_WRITE);
        //LOG_D("****webnet_module_system_dofile handled session->phase=%d",session->session_phase);

**Comment by aozima** [comment]
评估下优缺点，以及对其它类型的socket的影响吧。

**Comment by sheepsleep** [comment]
> 评估下优缺点，以及对其它类型的socket的影响吧。

[刚看了下W5500的驱动wiznet内部实现了poll](https://github.com/RT-Thread-packages/wiznet/blob/28692d020a3bf69258f3ee52d30218459983d906/src/wiz_af_inet.c#L26) 也就是支持select的  webnet_thread中select的超时设置的是0  select函数内部如果发现超时为0 则设为-1  也就是一直阻塞
webnet收到浏览器get请求后返回头部信息 并注册了session->session_ops = &_dofile_ops; 然后在下for次循环中到select又阻塞了所以_dofile_ops也不会被调用？导致浏览器一直等待html文件内容
可能是我理解有误 望指导 谢谢
