### ISSUE TITLE
closesocket when send keep-alive

### ISSUE THREAD

**Issue by zhaohengbo** [RT-Thread-packages/webnet#4]
In wn_session,webnet try to close the socket when session phase come to PHASE_CLOSE,even when it tells browser to KEEP-ALIVE.So in this situation some browser especially IE try to send RST after the first ack of FIN,then the lwip will maintain the connect and soon out of netconn if there are many request,we have to wait until close-timeout.

**Comment by Lawlieta** [comment]
Thanks for your feedback. In general, if the http client want to disconnect, the "connection: close" field needs to be send in the header information. Some of the operations in the sample may not send the field information which may cause your problem.  You can modify this to determine the problem, mainly modify the last parameter of the "webnet_session_set_header()" function

**Comment by BernardXiong** [comment]
@zhaohengbo 无敌少女，贴贴你QQ里的分析
