### ISSUE TITLE
Web软件包使用问题

### ISSUE THREAD

**Issue by BOBBOM** [RT-Thread-packages/webnet#8]
具体问题见论坛:
https://www.rt-thread.org/qa/forum.php?mod=viewthread&tid=10548&page=1#pid44682

**Comment by WKJay** [comment]
如何将keep-alive设置成普通模式

**Comment by Lawlieta** [comment]
感谢反馈，问题已经修复 https://github.com/RT-Thread-packages/webnet/pull/13
